version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: dotnet_demoApi_sqledge
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      SA_PASSWORD: "sqlServer@123" # 密碼需符合強度要求
    volumes:
      - ./sql_data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: dotnet_demoApi_redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: dotnet_demoApi_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: dotnet_demoApi_logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"  # Beats 輸入
      - "5000:5000"  # TCP 輸入
      - "9600:9600"  # API

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: dotnet_demoApi_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
